name: dockerize

on:
  push:
      # Sequence of patterns matched against refs/heads
      branches:
        # Push events on main branch
        - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: test go project
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Test
        run: CGO_ENABLED=0 go test -v ./...

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          tags: ghcr.io/coollision/synology-videostation-index-updater:latest, ghcr.io/coollision/synology-videostation-index-updater:${{ github.sha }},ghcr.io/coollision/synology-videostation-index-updater:0.0.4
          build-args: |
            buldtags=
            version=0.0.4
