name: Go

on:
  push:
    branches-ignore:
        - master
jobs:
  test:
    runs-on: ubuntu-latest
    name: test go project
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Test
      run: CGO_ENABLED=0 go test -v ./...

